### ISSUE TITLE
CK+ damage calculator not auto filling from .sav data

### ISSUE THREAD

**Issue by francoep** [emilyploszaj/emi.dev#1]
First, thanks for making this tool. I've been using it a lot and it is incredibly helpful.

But starting September 12, 2022, I've been unable to drag my .sav file into the web-browser to auto-populate the boxes.  It was working September 11, 2022.

I've tried clearing my browser caches & cookies, and tried using Microsoft Edge as well as Google Chrome and both are unable to load my .sav.  I can still manually add pokemon to the box on the website though.

Chrome -- 105.0.5195.102 (Official Build) (64-bit) (cohort: Stable)

Here is a link to the .sav that I have been using  -- https://drive.google.com/file/d/1nmimlurtb3Z7fzEUsd9wyXN8q569FIyH/view?usp=sharing

**Comment by emilyploszaj** [comment]
Are you on the lastest version of ck+? The save parser was updated for newbox

**Comment by francoep** [comment]
Ah HA! I was not! Thanks for the explanation.
